{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 208,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import glob\n",
    "\n",
    "file_name = glob.glob('../article/headline_noun_keyword*')\n",
    "\n",
    "keyword_df = []\n",
    "for file in file_name:\n",
    "    df = pd.read_pickle(file)\n",
    "    keyword_df.append(df)\n",
    "\n",
    "keyword_all = pd.concat(keyword_df, ignore_index = True)\n",
    "keyword_df = keyword_all[keyword_all['week'] <= 807]\n",
    "\n",
    "result_list = pd.Series([True for i in range(len(keyword_df))], index = [i for i in range(len(keyword_df))], name = 'result')\n",
    "keyword_df = pd.concat([keyword_df, result_list], axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 234,
   "metadata": {},
   "outputs": [],
   "source": [
    "all_week = list(set(keyword_df['week']))\n",
    "all_company = list(set(keyword_df['co']))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 235,
   "metadata": {},
   "outputs": [],
   "source": [
    "def return_pos_result(keyword):\n",
    "    global keyword_df\n",
    "    result_list = []\n",
    "    for pos in keyword_df.loc[:,'pos']:\n",
    "        pos = list(pos)\n",
    "        if set(pos) >= set(keyword):\n",
    "            result_list.append(True)\n",
    "        else:\n",
    "            result_list.append(False)\n",
    "    keyword_df.loc[:,'result'] = result_list\n",
    "\n",
    "def search_article(keyword, co, week):\n",
    "    global keyword_df\n",
    "    if co == 0:\n",
    "        co = all_company\n",
    "    if week == -1:\n",
    "        week = all_week\n",
    "    co_str = f'(co == {co}) and '\n",
    "    week_str = f'(week == {week}) and '\n",
    "    return_pos_result(keyword)\n",
    "    str_keyword = f'{co_str} {week_str} (result == True)'\n",
    "    df = keyword_df.query(str_keyword)\n",
    "    display(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 240,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>date</th>\n",
       "      <th>co</th>\n",
       "      <th>headline</th>\n",
       "      <th>week</th>\n",
       "      <th>pos</th>\n",
       "      <th>result</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>6879</th>\n",
       "      <td>2006.03.17. 오후 5:25</td>\n",
       "      <td>한국경제</td>\n",
       "      <td>이건희회장 자택 보유세 1억617만원</td>\n",
       "      <td>10</td>\n",
       "      <td>[이건희, 회장, 자택, 보유, 세, 억, 만, 원]</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6969</th>\n",
       "      <td>2006.03.18. 오전 9:02</td>\n",
       "      <td>매일경제</td>\n",
       "      <td>이건희회장 자택 보유세 1억원대</td>\n",
       "      <td>10</td>\n",
       "      <td>[이건희, 회장, 자택, 보유, 세, 억, 원대]</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11344</th>\n",
       "      <td>2006.04.27. 오후 10:45</td>\n",
       "      <td>한겨레</td>\n",
       "      <td>분당 39%나 올라…이건희 회장 집 85억 ‘최고’</td>\n",
       "      <td>16</td>\n",
       "      <td>[분당, 이건희, 회장, 집, 억, 최고]</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11352</th>\n",
       "      <td>2006.04.27. 오후 8:51</td>\n",
       "      <td>세계일보</td>\n",
       "      <td>이건희회장 이태원1동 집 최고가</td>\n",
       "      <td>16</td>\n",
       "      <td>[이건희, 회장, 이태원, 동, 집, 최고]</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11354</th>\n",
       "      <td>2006.04.27. 오후 7:15</td>\n",
       "      <td>경향신문</td>\n",
       "      <td>이건희회장 이태원동 집 85억 ‘최고’</td>\n",
       "      <td>16</td>\n",
       "      <td>[이건희, 회장, 이태, 원동, 집, 억, 최고]</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1065316</th>\n",
       "      <td>2021.06.25. 오후 4:08</td>\n",
       "      <td>이데일리</td>\n",
       "      <td>故 이건희 이태원 단독주택 ‘210억원’ 매물로</td>\n",
       "      <td>807</td>\n",
       "      <td>[이건희, 이태원, 단독, 주택, 억, 원, 매물]</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1065325</th>\n",
       "      <td>2021.06.25. 오후 3:58</td>\n",
       "      <td>머니S</td>\n",
       "      <td>고 이건희 이태원 단독주택 210억원에 매물로 나왔다</td>\n",
       "      <td>807</td>\n",
       "      <td>[이건희, 이태원, 단독, 주택, 억, 원, 매물]</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1065332</th>\n",
       "      <td>2021.06.25. 오후 3:26</td>\n",
       "      <td>서울경제</td>\n",
       "      <td>故 이건희 회장 이태원 주택 210억에 매물로 나왔다</td>\n",
       "      <td>807</td>\n",
       "      <td>[이건희, 회장, 이태원, 주택, 억, 매물]</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1065383</th>\n",
       "      <td>2021.06.25. 오후 1:31</td>\n",
       "      <td>조선비즈</td>\n",
       "      <td>단독 故 이건희 회장 이태원동 주택 매물로</td>\n",
       "      <td>807</td>\n",
       "      <td>[단독, 이건희, 회장, 이태원동, 주택, 매물]</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1065649</th>\n",
       "      <td>2021.06.26. 오전 3:01</td>\n",
       "      <td>동아일보</td>\n",
       "      <td>故 이건희 회장 이태원 주택 210억에 매물로</td>\n",
       "      <td>807</td>\n",
       "      <td>[이건희, 회장, 이태원, 주택, 억, 매물]</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>223 rows × 6 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                         date    co                       headline  week  \\\n",
       "6879      2006.03.17. 오후 5:25  한국경제           이건희회장 자택 보유세 1억617만원    10   \n",
       "6969      2006.03.18. 오전 9:02  매일경제              이건희회장 자택 보유세 1억원대    10   \n",
       "11344    2006.04.27. 오후 10:45   한겨레   분당 39%나 올라…이건희 회장 집 85억 ‘최고’    16   \n",
       "11352     2006.04.27. 오후 8:51  세계일보              이건희회장 이태원1동 집 최고가    16   \n",
       "11354     2006.04.27. 오후 7:15  경향신문          이건희회장 이태원동 집 85억 ‘최고’    16   \n",
       "...                       ...   ...                            ...   ...   \n",
       "1065316   2021.06.25. 오후 4:08  이데일리     故 이건희 이태원 단독주택 ‘210억원’ 매물로   807   \n",
       "1065325   2021.06.25. 오후 3:58   머니S  고 이건희 이태원 단독주택 210억원에 매물로 나왔다   807   \n",
       "1065332   2021.06.25. 오후 3:26  서울경제  故 이건희 회장 이태원 주택 210억에 매물로 나왔다   807   \n",
       "1065383   2021.06.25. 오후 1:31  조선비즈        단독 故 이건희 회장 이태원동 주택 매물로   807   \n",
       "1065649   2021.06.26. 오전 3:01  동아일보      故 이건희 회장 이태원 주택 210억에 매물로   807   \n",
       "\n",
       "                                   pos  result  \n",
       "6879     [이건희, 회장, 자택, 보유, 세, 억, 만, 원]    True  \n",
       "6969       [이건희, 회장, 자택, 보유, 세, 억, 원대]    True  \n",
       "11344          [분당, 이건희, 회장, 집, 억, 최고]    True  \n",
       "11352         [이건희, 회장, 이태원, 동, 집, 최고]    True  \n",
       "11354      [이건희, 회장, 이태, 원동, 집, 억, 최고]    True  \n",
       "...                                ...     ...  \n",
       "1065316   [이건희, 이태원, 단독, 주택, 억, 원, 매물]    True  \n",
       "1065325   [이건희, 이태원, 단독, 주택, 억, 원, 매물]    True  \n",
       "1065332      [이건희, 회장, 이태원, 주택, 억, 매물]    True  \n",
       "1065383    [단독, 이건희, 회장, 이태원동, 주택, 매물]    True  \n",
       "1065649      [이건희, 회장, 이태원, 주택, 억, 매물]    True  \n",
       "\n",
       "[223 rows x 6 columns]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "search_article([\"이건희\"],0,-1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
